name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: files_mediaviewer

jobs:
  get-vars:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ env.APP_NAME }}
    steps:
      - name: Set variables
        run: |
          echo "App name $APP_NAME"

  semantic-git-messages:
    name: Commits
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@main

  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest
    needs:
      - get-vars
    steps:
      - name: Run JS Lint
        run: |
          cd apps/${{ inputs.app-name }}
          make test-js-style
